---
- hosts: galera
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: ['mariadb-server', 'galera-3', 'mariadb-client', 'rsync']
        state: present
        update_cache: yes

    - name: Configure MariaDB for Galera
      template:
        src: my.cnf.j2
        dest: /etc/mysql/my.cnf
      notify: restart mariadb

    - name: Create Galera configuration
      template:
        src: galera.cnf.j2
        dest: /etc/mysql/conf.d/galera.cnf
      notify: restart mariadb

    - name: Ensure MariaDB is started and enabled
      service:
        name: mariadb
        state: started
        enabled: yes

  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted

