---
- hosts: loadbalancer
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

    - name: Ensure HAProxy is started and enabled
      service:
        name: haproxy
        state: started
        enabled: yes

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
